
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Louisa
 */
public class CekIdeal extends javax.swing.JFrame {
    
    String temp = "";
    Double bt,tb,bb;

    /**
     * Creates new form CekIdeal
     */
    public CekIdeal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldTinggi = new javax.swing.JTextField();
        jTextFieldBerat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButtonPerempuan = new javax.swing.JRadioButton();
        jRadioButtonLaki = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cek Ideal Tubuh");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 250, 50);

        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 120, 80, 30);

        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 80, 30);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 80, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 260, 120, 30);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 260, 120, 30);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 260, 120, 30);

        jLabel6.setText("Berat Badan Ideal Anda Adalah");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 320, 180, 30);

        jLabel7.setText("Hasil Dianogsa Kesehatan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 360, 230, 30);

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 430, 510, 30);

        jLabel9.setText("jLabel8");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 390, 510, 30);

        jLabel10.setText("__________");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 320, 80, 30);

        jLabel11.setText(":");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 200, 40, 30);

        jLabel12.setText(":");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 80, 50, 30);

        jLabel13.setText(":");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 120, 40, 30);

        jLabel14.setText(":");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(130, 160, 50, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 80, 260, 30);

        jTextFieldTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTinggiActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTinggi);
        jTextFieldTinggi.setBounds(170, 120, 90, 30);

        jTextFieldBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBeratActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBerat);
        jTextFieldBerat.setBounds(170, 160, 90, 30);

        jLabel15.setText("Kg");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(300, 320, 60, 30);

        jLabel16.setText(" Cm");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(270, 120, 60, 30);

        jLabel17.setText(" Kg");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(270, 160, 50, 30);

        buttonGroupJk.add(jRadioButtonPerempuan);
        jRadioButtonPerempuan.setText("Perempuan");
        jPanel1.add(jRadioButtonPerempuan);
        jRadioButtonPerempuan.setBounds(320, 200, 120, 30);
        jRadioButtonPerempuan.getAccessibleContext().setAccessibleParent(jTextFieldBerat);

        buttonGroupJk.add(jRadioButtonLaki);
        jRadioButtonLaki.setText("Laki-laki");
        jPanel1.add(jRadioButtonLaki);
        jRadioButtonLaki.setBounds(170, 200, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 470);

        setBounds(0, 0, 520, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextFieldTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTinggiActionPerformed

    private void jTextFieldBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBeratActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
            if(jTextFieldBerat.getText().equals("")||jTextFieldTinggi.getText().equals("")||jTextField2.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Kotak Isian Harus Diisi, tidak boleh kosong");
            }else if(jRadioButtonLaki.isSelected()||jRadioButtonPerempuan.isSelected())
            
                try
                { 
                    Proses(); 
                }
            catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Masukkan Dengan benar");
                    } else { JOptionPane.showMessageDialog(null, "Silahkan pilih jenis kelamin"); }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText("");
        jTextFieldBerat.setText("");
        jTextFieldTinggi.setText("");
        buttonGroupJk.clearSelection();
        jLabel10.setText("");
        jLabel9.setText("");
        jLabel8.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekIdeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLaki;
    private javax.swing.JRadioButton jRadioButtonPerempuan;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBerat;
    private javax.swing.JTextField jTextFieldTinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
         //To change body of generated methods, choose Tools | Templates.
         tb = Double.valueOf(jTextFieldTinggi.getText());
         bb = Double.valueOf(jTextFieldBerat.getText());
         
         if(jRadioButtonPerempuan.isSelected())
        {
           bt = (tb-100) *1;     
        }else if (jRadioButtonLaki.isSelected())
        {
            bt = (tb - 104) *1;
        }
         temp = Double.toString(bt.intValue());
         if(bt<bb)
         {
             jLabel10.setText(temp);
             jLabel9.setText("Maaf "+jTextField2.getText()+" , Sepertinya Anda Overweight :(");
             jLabel8.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
         }else if(bt>bb)
         {
             jLabel10.setText(temp);
             jLabel9.setText("Maaf "+jTextField2.getText()+" , Sepertinya Anda Underweight :(");
             jLabel8.setText("Banyaklah berolahraga dan hindari makanan berkarbohidrat");
         }else
         {
             jLabel10.setText(temp);
             jLabel9.setText("Maaf "+jTextField2.getText()+" , Sepertinya Anda sudah ideal :(");
             jLabel8.setText("Lanjutkan polo makan yang teratur dan gaya hidup sehat");
         }
         
    }
}
