
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Louisa
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTinggi = new javax.swing.JTextField();
        jTextFieldPanjang = new javax.swing.JTextField();
        jTextFieldLebar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonBalok = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldSisi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonKubus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldJari = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonBola = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setText("Masukkan Tinggi");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 120, 160, 30);

        jLabel3.setText("Masukkan Panjang");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 160, 30);

        jLabel4.setText("Masukkan Lebar");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 160, 30);

        jLabel5.setText(":");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 120, 40, 30);

        jLabel6.setText(":");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 20, 40, 30);

        jLabel7.setText(":");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 70, 40, 30);
        jPanel2.add(jTextFieldTinggi);
        jTextFieldTinggi.setBounds(200, 120, 150, 30);
        jPanel2.add(jTextFieldPanjang);
        jTextFieldPanjang.setBounds(200, 20, 150, 30);
        jPanel2.add(jTextFieldLebar);
        jTextFieldLebar.setBounds(200, 70, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("cm");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 130, 34, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 30, 34, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("cm");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(360, 80, 34, 17);

        jButtonBalok.setText("Hitung");
        jButtonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalokActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBalok);
        jButtonBalok.setBounds(200, 170, 150, 30);

        jLabel11.setText("Tidak Boleh Kosong");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(400, 70, 200, 50);

        jLabel17.setText("Panjang, Lebar, Tinggi ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(400, 40, 200, 50);

        jTabbedPane1.addTab("Balok", jPanel2);

        jPanel3.setLayout(null);
        jPanel3.add(jTextFieldSisi);
        jTextFieldSisi.setBounds(20, 60, 140, 40);

        jLabel12.setText("cm");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(170, 74, 50, 20);

        jButtonKubus.setText("Volume");
        jButtonKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKubusActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonKubus);
        jButtonKubus.setBounds(20, 120, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Masukkan Panjang Sisi");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 10, 230, 40);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(20, 60, 140, 40);

        jLabel14.setText("cm");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(170, 74, 50, 20);

        jButton3.setText("Volume");
        jPanel3.add(jButton3);
        jButton3.setBounds(20, 120, 110, 30);

        jLabel20.setText("Tidak Boleh Kosong");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(210, 80, 200, 50);

        jLabel21.setText("Sisi");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(210, 50, 200, 50);

        jTabbedPane1.addTab("Kubus", jPanel3);

        jPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Masukkan Panjang Jari-jari");
        jLabel15.setToolTipText("");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(20, 10, 230, 40);
        jPanel4.add(jTextFieldJari);
        jTextFieldJari.setBounds(20, 60, 140, 40);

        jLabel16.setText("cm");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(170, 74, 50, 20);

        jButtonBola.setText("Volume");
        jButtonBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonBola);
        jButtonBola.setBounds(20, 120, 110, 30);

        jLabel18.setText("Tidak Boleh Kosong");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(210, 80, 200, 50);

        jLabel19.setText("Jari-jari");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(210, 50, 200, 50);

        jTabbedPane1.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 600, 250);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Mencari Volum Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 390, 30);

        setBounds(0, 0, 616, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(jTextFieldPanjang.getText());
        lebar = Integer.parseInt(jTextFieldLebar.getText());
        tinggi = Integer.parseInt(jTextFieldTinggi.getText());
        int hasil = panjang * lebar * tinggi;
        try
        {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah: "+panjang+" x "+lebar+" x "+tinggi+" = "+hasil+" Cm3","VOLUME", JOptionPane.INFORMATION_MESSAGE);   
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBalokActionPerformed

    private void jButtonKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(jTextFieldSisi.getText());
        int hasil = sisi * sisi*sisi;
        try
        {
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah: "+sisi+" x "+sisi+" x "+sisi +"= "+ hasil+" Cm3","VOLUME",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKubusActionPerformed

    private void jButtonBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaActionPerformed
        // TODO add your handling code here:
        int jari ;
        jari = Integer.parseInt(jTextFieldJari.getText());
        float hasil = (float) (3/4*3.14*jari*jari*jari) ;
         try
        {
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah: 3/4 x 3,14 x"+jari+" x "+jari+" x "+jari +"= "+ hasil+" Cm3","VOLUME",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBalok;
    private javax.swing.JButton jButtonBola;
    private javax.swing.JButton jButtonKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldJari;
    private javax.swing.JTextField jTextFieldLebar;
    private javax.swing.JTextField jTextFieldPanjang;
    private javax.swing.JTextField jTextFieldSisi;
    private javax.swing.JTextField jTextFieldTinggi;
    // End of variables declaration//GEN-END:variables
}
